import csv
import os

from utilities import sqlutils, stringutils, globals

# This script imports data from patients who agreed to participate in the IBD registry
# Data is imported from IBD_Registry_Participant_List_2014-02-21.csv
# Only the following columns are imported:
#       MRN (Patient ID)
#       Date of Birth (converted to year of birth)
#       Race
#       Ethnic group
#       Employment Status
# This script populates the following three table in ibd2015dw database:
#       patient
# Excel to database field mappings are defined in mappings/2015/patients.json


# Get a list of mapped fields
map = stringutils.getJsonMapping(2017, 'patients')


#Import patient information
filename = map["FILENAME"] # Source filename (defined in mappings JSON file)

os.chdir(globals.CSV_SOURCE_FOLDER);


# Start patient data import
counter = 0
with open(os.path.abspath(filename), 'rU') as f:
    for row in csv.reader(f):
        if any(row) and counter > 0:
            # Even though the primary key used for patients' identifiers is auto-generated by MySQL
            # (sequential number), we still store the original MRN encry\pted with MD5 hash
            # to link back to external records and to identify new patient records.
            rawMrn = stringutils.prefixZeros(row[map['MRN']], globals.MAX_MRN_LENGTH)
            #print(rawMrn)
            mrn = stringutils.computeMD5hash(rawMrn)
            print(mrn)

            # gender is a binary field.  M (Male) is 0 and F (female) is 1
            gender = 1 if row[map['GENDER']].strip() == 'F' else 0

            # original files store patients' birth dates.  However, due to IRB restrictions,
            # we can only keep birth years.

            birthYear = stringutils.yearFromStringDate(row[map['BIRTH_DATE']])

            # Bit field specifying if the patient participating in the study is still alive.
            # Alive is 1, dead is 0
            isAlive = 1 if row[map['PATIENT_STATUS']] == 'Alive' else 0

            race = 'Unknown' if row[map['RACE']].strip() == "" else row[map['RACE']]
            print(race)

            # Ethnic group values are stored in ethnicgroup table
            ethnicGroup = 'Unknown' if row[map['ETHNIC_GROUP']].strip() == "" else row[map['ETHNIC_GROUP']]

            # Employment status values are store in employementstatus table
            emplStatus = 'Unknown' if row[map['EMPLOYMENT_STATUS']].strip() == "" else row[map['EMPLOYMENT_STATUS']]

            # Marital Status
            maritalStatus = row[map["MARITAL_STATUS"]]
            print(maritalStatus)


            sql = "INSERT INTO patient (encryptedPatientID,gender,birthYear,isAlive,"
            sql += "race, ethnicGroup, employementStatus, maritalStatus) "
            sql += "VALUES (%s,%s,%s,%s,%s,%s,%s,%s)"
            sqlutils.execMysqlQuery(sql, (mrn, gender, birthYear, isAlive, race, ethnicGroup, emplStatus, maritalStatus))


        counter = counter + 1  # Note - counter is only used to ignore the first row of the spreadsheet (contains column headings)



