import csv
import os

from utilities import sqlutils, stringutils, globals



# This script imports allergy data for existing study patients
# Data is imported from IBD Registry Patient Allergy Information 2014-02-21.csv
#       PATIENT_ID (MRN)
#       DESCRIPTION
#       SEVERITY
#       REACTION
# This script populates the following table in ibd_import database:
#       allergy
#       patient_allergy
# Excel to database field mappings are defined in mappings/2014/allergy.json


# Get a list of mapped fields
map = stringutils.getJsonMapping(globals.CURRENT_YEAR, 'allergy')


filename = map["FILENAME"] # Source filename (defined in mappings JSON file)

os.chdir(globals.CSV_SOURCE_FOLDER);


# Fill dictionaries
sql = "SELECT patientID, encryptedPatientID FROM patient;"
patients = sqlutils.tableToDictionary(sql, 1, 0)



# Start patient_allergy data import
counter = 0
with open(os.path.abspath(filename), 'rU') as f:
    for row in csv.reader(f):
        if any(row) and counter > 0:
            # Even though the primary key used for patients' identifiers is auto-generated by MySQL
            # (sequential number), we still store the original MRN encrypted with MD5 hash
            # to link back to external records and to identify new patient records.
            rawMrn = stringutils.prefixZeros(row[map['MRN']], globals.MAX_MRN_LENGTH)
            mrn = stringutils.computeMD5hash(rawMrn)

            if mrn in patients.keys():
                patientID = patients[mrn]
                allergyName = row[map['DESCRIPTION']].strip()

                # Severity
                severity = row[map['SEVERITY']].strip()

                # Reaction
                reaction = row[map['REACTION']]

                # Insert only if record does not exist in the database, otherwise update.
                # ***** NOTE: We are making an assumption that the combination of patientID and allergyID is unique -
                # ***** in other words, we are assuming that each patient would not have duplicate records for the same
                # ***** type of allergy
                sql = "INSERT INTO allergies (fk_patientID,allergy,reaction,severity) VALUES (%s, %s, %s, %s);"
                sqlutils.execMysqlQuery(sql, (str(patientID), allergyName, severity, reaction))



        counter = counter + 1  # Note - counter is only used to ignore the first row of the spreadsheet (contains column headings)


