import csv
import os


from utilities import sqlutils, stringutils, globals


# This script imports diagnosis data for existing study patients
# Data is imported from IBD_Reg_Pts_w_Office_Phone_Email_2014-03-04.csv
# The following columns are imported:
#       PAT_ID (MRN)
#       ENC_TYPE_C
#       ENC_TYPE_NAME
#       CONTACT_DATE
#       DEPT_ID
#       DEPT_NAME
#       VISIT_PROV_ID
#       EMPI_ID
#       MEDIPAC_ID
# This script populates the following two tables in ibd_import database:
#       encountertype
#       department
#       patient_encounters
# Excel to database field mappings are defined in mappings/2014/encounters.json


# Get a list of mapped fields
map = stringutils.getJsonMapping(globals.CURRENT_YEAR, 'encounters')

# Populate dictionary objects.  This greatly improves performance over
# looking up values for each INSERT or UPDATE statement.  Also helps prevent duplicates.
sql = "SELECT patientID, encryptedPatientID FROM patient;"
patients = sqlutils.tableToDictionary(sql, 1, 0)


filename = map["FILENAME"] # Source filename (defined in mappings JSON file)

os.chdir(globals.CSV_SOURCE_FOLDER);


# Start patient_encounters data import
counter = 0
with open(os.path.abspath(filename), 'rU') as f:
    for row in csv.reader(f):
        if any(row) and counter > 0:
            # Even though the primary key used for patients' identifiers is auto-generated by MySQL
            # (sequential number), we still store the original MRN encrypted with MD5 hash
            # to link back to external records and to identify new patient records.
            rawMrn = stringutils.prefixZeros(row[map['MRN']], globals.MAX_MRN_LENGTH)
            mrn = stringutils.computeMD5hash(rawMrn)

            if mrn in patients.keys():
                patientID = patients[mrn]
                encTypeName = row[map['ENC_TYPE_NAME']]
                encTypeCode = row[map['ENC_TYPE_C']]

                deptID = row[map['DEPT_ID']]
                if str(deptID).isdigit() == False:
                    deptID = 0
                deptName = row[map['DEPT_NAME']]
                contactDate = stringutils.convertDateToMySQL(row[map['CONTACT_DATE']].strip())
                visitProviderID = row[map['VISIT_PROV_ID']]

                sql = "INSERT INTO encounters(fk_patientID,encounterCode,encounterType,contactDate,deptID,deptName,visitProviderID) "
                sql += "VALUES (%s,%s,%s,%s,%s,%s,%s);"
                sqlutils.execMysqlQuery(sql, (patientID, encTypeCode, encTypeName, contactDate, deptID, deptName, visitProviderID))


        counter = counter + 1  # Note - counter is only used to ignore the first row of the spreadsheet (contains column headings)

