group_map = {
    'C-REACTIVE PROTEIN': 'crp',
    'HIGH SENSITIVITY CRP': 'crp',
    'CRP QUANTITATION': 'crp',
    'CARDIO CRP': 'crp',
    'SEDRATE - AUTOMATED': 'esr',
    'ESR': 'esr',
    'WESTERGREN ESR': 'esr',
    'WESTERGREN SED RATE': 'esr',
    'SED RATE': 'esr',
    'COMP METABOLIC PANEL': 'albumin',
    'RENAL FUNCTION PANEL (OO)': 'albumin',
    'HEPATIC FUNCTION PANEL': 'albumin',
    'ALBUMIN': 'albumin',
    'ALBUMIN (OO)': 'albumin',
    'LIVER TRANSPLANT POST-OP LONG LAB SET': 'albumin',
    'HILLMAN COMPREHENSIVE COMP PANEL': 'albumin',
    'COMP METABOLIC PANEL W/EGFR': 'albumin',
    'TOTAL PROTEIN ELECTROPHORESIS, SERUM': 'albumin',
    'PROTEIN ELECTROPHORESIS, SERUM': 'albumin',
    'ADD ON HEPATIC FUNCTION PANEL': 'albumin',
    'CMP & GFR(QUEST ONLY)': 'albumin',
    'COMMUNITY HEALTH SCREEN W/LDL': 'albumin',
    'SMALL BOWEL TRANSPLANT POST-OP LAB SET': 'albumin',
    'RENAL TRANSPLANT POST-OP LONG LAB SET': 'albumin',
    'HEPATORENAL PANEL': 'albumin',
    'TOTAL PROTEIN ELECT. (OO)': 'albumin',
    'SERUM PROTEIN ELEC WITH GRAPH': 'albumin',
    'CHEM-SCREEN PANEL': 'albumin',
    'AUTOLOGOUS LYMPHOMA': 'albumin',
    'LIVER TRANSPLANT POST-OP SHORT LAB SET': 'albumin',
    'CMP W/EGFR': 'albumin',
    'CHEM-SCREEN PNL+HDL,TIBC (QUEST)': 'albumin',
    'MULTIPLE MYELOMA PANEL': 'albumin',
    'PROTEIN ELECTRO/TPROT W/RFX, SERUM': 'albumin',
    'COMP METABOLIC PANEL W/O EGFR': 'albumin',
    'TESTOSTERONE,FREE,BIOAVAIL/TOT': 'albumin',
    'BASIC METABOLIC PANEL': 'albumin',
    'HEPATIC FUNCTION PANEL WITHOUT TOTAL PROTEIN': 'albumin',
    'VITAMIN D, 25-HYDROXY': 'vitamin_d',
    'HGB': 'hemoglobin',
    'HEMOGLOBIN-PLASMA': 'hemoglobin',
    'HEMOGLOBIN-ARTERIAL': 'hemoglobin',
    'BEDSIDE HEMOGLOBIN POCT': 'hemoglobin',
    'HEMOGLOBIN - MIXED VENOUS': 'hemoglobin',
    'TOTAL HGB(VENOUS)': 'hemoglobin',
    'HEMOGLOBIN-VENOUS': 'hemoglobin',
    'TOTAL HEMOGLOBIN': 'hemoglobin',
    'HEMOGLOBIN (POCT)': 'hemoglobin',
    'HEMOGLOBIN CAPILLARY (POC)': 'hemoglobin',
    'HEMOGLOBIN ISTAT': 'hemoglobin',
    'HEMOGLOBIN': 'hemoglobin',
    'THB (HEMOGLOBIN)': 'hemoglobin',
    'CBC & DIFF INC PLATELET': 'eos',
    'CBC AND DIFF W/ PLATELETS': 'eos',
    'MANUAL DIFFERENTIAL': 'eos',
    'LIVER TRANSPLANT POST-OP LONG LAB SET': 'eos',
    'LIVER TRANSPLANT POST-OP SHORT LAB SET': 'eos',
    'OBSTETRIC PANEL': 'eos',
    'DIFFERENTIAL (MANUAL)': 'eos',
    'VISUAL DIFFERENTIAL': 'eos',
    'DIFFERENTIAL': 'eos',
    'CBC/MANUAL DIFF-LAB USE ONLY': 'eos',
    'OBSTETRIC PANEL W/HIV': 'eos',
    'DIFFERENTIAL (AUTO)': 'eos',
    'OBSTETRIC PANEL (MAGEE ONLY)': 'eos',
    'SMALL BOWEL TRANSPLANT POST-OP LAB SET': 'eos',
    'OBSTETRIC PANEL W/REFLEX': 'eos',
    'CBC/AUTO DIFF, ONCOLOGY': 'eos',
    'CBC/DIFF AMBIGIOUS DEFAULT': 'eos',
    'CBC AND DIFF W/ PLATELET': 'eos',
    'CBC WITHOUT DIFF W/ PLATELETS': 'eos',
    'CBC AND DIFF W/O PLATELETS': 'eos',
    'RENAL TRANSPLANT POST-OP LONG LAB SET': 'eos',
    'RENAL TRANSPLANT POST-OP SHORT LAB SET': 'eos',
    'PRENATAL PANEL': 'eos',
    'CBC AND DIFF': 'eos',
    'MULTIPLE MYELOMA PANEL': 'eos',
    'COMMUNITY HEALTH SCREEN W/LDL': 'eos',
    'DIFF ADD ONTO CBCP': 'eos',
    'AUTOLOGOUS LYMPHOMA': 'eos',
    'ABS EOSINOPHILS': 'eos',
    'EOSINOPHILS': 'eos',
    'AUTO. ABSOL. EOSIN': 'eos',
    'AUTOMATED EOSIN %': 'eos',
    'ABSOLUTE EOS': 'eos',
    'EOS %': 'eos',
    'AUTO ABSOL EOSIN': 'eos',
    'AUTOMATED EOSIN%': 'eos',
    'ABS EOS': 'eos',
    'EOSINOPHIL': 'eos',
    'EOS#': 'eos',
    'ABSOLUTE EOSINOPHILS': 'eos',
    'EOSINOPHILS, ABS': 'eos',
    'EOS': 'eos',
    'CBC & DIFF INC PLATELET': 'monocytes',
    'CBC AND DIFF W/ PLATELETS': 'monocytes',
    'MANUAL DIFFERENTIAL': 'monocytes',
    'LIVER TRANSPLANT POST-OP LONG LAB SET': 'monocytes',
    'LIVER TRANSPLANT POST-OP SHORT LAB SET': 'monocytes',
    'OBSTETRIC PANEL': 'monocytes',
    'DIFFERENTIAL (MANUAL)': 'monocytes',
    'VISUAL DIFFERENTIAL': 'monocytes',
    'DIFFERENTIAL': 'monocytes',
    'CBC/MANUAL DIFF-LAB USE ONLY': 'monocytes',
    'OBSTETRIC PANEL W/HIV': 'monocytes',
    'DIFFERENTIAL (AUTO)': 'monocytes',
    'OBSTETRIC PANEL (MAGEE ONLY)': 'monocytes',
    'CBC WITHOUT DIFF W/ PLATELETS': 'monocytes',
    'SMALL BOWEL TRANSPLANT POST-OP LAB SET': 'monocytes',
    'VISUAL DIFF ONCOLOGY': 'monocytes',
    'OBSTETRIC PANEL W/REFLEX': 'monocytes',
    'CBC/AUTO DIFF, ONCOLOGY': 'monocytes',
    'CBC/DIFF AMBIGIOUS DEFAULT': 'monocytes',
    'CBC AND DIFF W/ PLATELET': 'monocytes',
    'CBC AND DIFF W/O PLATELETS': 'monocytes',
    'RENAL TRANSPLANT POST-OP LONG LAB SET': 'monocytes',
    'RENAL TRANSPLANT POST-OP SHORT LAB SET': 'monocytes',
    'CBC, ONCOLOGY': 'monocytes',
    'PRENATAL PANEL': 'monocytes',
    'CBC AND DIFF': 'monocytes',
    'MULTIPLE MYELOMA PANEL': 'monocytes',
    'COMMUNITY HEALTH SCREEN W/LDL': 'monocytes',
    'DIFF ADD ONTO CBCP': 'monocytes',
    'AUTOLOGOUS LYMPHOMA': 'monocytes',
    'ABS MONOCYTES': 'monocytes',
    'MONOCYTES': 'monocytes',
    'AUTO. ABSOL. MONOS': 'monocytes',
    'AUTOMATED MONOS %': 'monocytes',
    'MONOS %': 'monocytes',
    'AUTO ABSOL MONOS': 'monocytes',
    'AUTOMATED MONO%': 'monocytes',
    'MONOCYTE': 'monocytes',
    'ABS MONO': 'monocytes',
    'MONO#': 'monocytes',
    'MONOCYTES (%) @': 'monocytes',
    'ABSOLUTE MONOCYTES': 'monocytes',
    'ABS MONOCYTE': 'monocytes',
    'MONO': 'monocytes',
    'MONOCYTES @': 'monocytes',
    'MONOCYTES, ABS': 'monocytes'
}


def get_lab_group(component_name):
    if component_name in group_map:
        return group_map[component_name]

    return ''
